services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./sqlite:/usr/src/app/sqlite
    ports:
      - 3000:3000
    depends_on:
      - bit
  bit:
    image: sjdonado/bit
    environment:
      APP_URL: http://localhost:4001
      ADMIN_NAME: 'Admin'
      ADMIN_API_KEY: 'secure_12345'
    volumes:
      - sqlite_data:/app/sqlite
    ports:
      - 4000:4000

volumes:
  sqlite_data:
