name: Run tests

on:
  pull_request:
    branches: [master]

env:
  SPOTIFY_AUTH_URL: https://accounts.spotify.com/api/token
  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
  SPOTIFY_CLIENT_SECRET: ${{ secrets.YOUTUBE_COOKIES }}
  SPOTIFY_CLIENT_VERSION: ${{ secrets.SPOTIFY_CLIENT_VERSION }}
  SPOTIFY_API_URL: https://api.spotify.com/v1/search
  YOUTUBE_MUSIC_URL: https://music.youtube.com/search
  YOUTUBE_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}
  DEEZER_API_URL: https://api.deezer.com/search
  APPLE_MUSIC_API_URL: https://music.apple.com/ca
  SOUNDCLOUD_BASE_URL: https://soundcloud.com
  TIDAL_BASE_URL: https://listen.tidal.com

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Run integration tests
        run: bun run test
