name: Run tests

on:
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      bit:
        image: sjdonado/bit
        env:
          APP_URL: http://localhost:4001
          ADMIN_NAME: 'Admin'
          ADMIN_API_KEY: 'secure_12345'
        ports:
          - 4000:4000
    steps:
      - uses: actions/checkout@v4
      - name: Load environment variables
        run: |
          while read -r line; do
            # skip empty and comment lines
            if [ -n "$line" ] && [ "${line:0:1}" != "#" ]; then
              echo "$line" >> $GITHUB_ENV
            fi
          done < .env.test
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Run integration tests
        run: bun run test:ci
