name: Run tests

on:
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      bit:
        image: sjdonado/bit
        env_file: .env.test
        ports:
          - 4000:4000
        options: >-
          --volume sqlite_data:/app/sqlite

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Run integration tests
        run: bun run test
        env_file: .env.test

volumes:
  sqlite_data:
