name: Run tests

on:
  pull_request:
    branches: [master]

env:
  SPOTIFY_API_URL: https://api.spotify.com/v1/search
  SPOTIFY_AUTH_URL: https://accounts.spotify.com/api/token
  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
  SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
  SPOTIFY_CLIENT_VERSION: ${{ secrets.SPOTIFY_CLIENT_VERSION }}
  TIDAL_BASE_URL: https://tidal.com/browse
  TIDAL_API_URL: https://openapi.tidal.com/v2/searchresults
  TIDAL_AUTH_URL: https://auth.tidal.com/v1/oauth2/token
  TIDAL_CLIENT_ID: ${{ secrets.TIDAL_CLIENT_ID }}
  TIDAL_CLIENT_SECRET: ${{ secrets.TIDAL_CLIENT_SECRET }}
  YOUTUBE_API_URL: https://content-youtube.googleapis.com/youtube/v3/search
  YOUTUBE_MUSIC_BASE_URL: https://music.youtube.com
  YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
  DEEZER_API_URL: https://api.deezer.com/search
  APPLE_MUSIC_API_URL: https://music.apple.com/ca
  SOUNDCLOUD_BASE_URL: https://soundcloud.com
  URL_SHORTENER_API_URL: http://localhost:4000/api/links
  URL_SHORTENER_API_KEY: secure_12345

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      app:
        build: .
        env:
          APP_URL: http://localhost:3000
        ports:
          - 3000:3000
        options: >-
          --volume ./sqlite:/usr/src/app/sqlite
        depends-on:
          - bit
      bit:
        image: sjdonado/bit
        env:
          APP_URL: http://localhost:4001
          ADMIN_NAME: 'Admin'
          ADMIN_API_KEY: 'secure_12345'
        ports:
          - 4000:4000
        options: >-
          --volume sqlite_data:/app/sqlite

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Run integration tests
        run: bun run test

volumes:
  sqlite_data:
